name: Setup and Install
description: Common action for setting up Node and PNPM

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        version: '20'
        cache: 'pnpm'

    - shell: bash
      run: pnpm install
