name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: ${{ github.repository_owner == 'ponraaj' }}
    name: Create PR for Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - name: Check for errors
        run: pnpm check

      - name: Build package
        run: pnpm build

      - name: Configure NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Create PR && Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore(release): version packages'
          title: 'chore(release): version packages'
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Version bumps
        if: steps.changesets.outputs.hasChangesets == 'true'
        run: npx changeset version

      - name: Sync Lockfile
        if: steps.changesets.outputs.hasChangesets == 'true'
        run: pnpm install

      - name: Publish to NPM
        if: steps.changesets.outputs.hasChangesets == 'true'
        run: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NODE_ENV: 'production'
